miraiboot:
  bots:
    -
      account: 123
      password:
        kind: PLAIN
        value: pwd
      configuration:
        protocol: ANDROID_PHONE
        device: device.json
    -
      account: 123
      password:
        kind: PLAIN
        value: pwd
      configuration:
        protocol: ANDROID_PHONE
        device: device.json
  logger:
    network: false