miraiboot:
  bots:
    -
      account: 123 # qq号
      password:
        kind: PLAIN # 密码类型 目前仅支持PLAIN纯文本类型
        value: pwd # qq密码
      configuration:
        protocol: ANDROID_PHONE # qq登录协议 支持 ANDROID_PHONE ANDROID_PAD ANDROID_WATCH
        device: device.json # 设备信息文件名
    # 可以配置多个 在@EventFilter中修改bot字段可以指定不同的bot处理事件
    - account: 123 # qq号
      password:
        kind: PLAIN # 密码类型 目前仅支持PLAIN纯文本类型
        value: pwd # qq密码
      configuration:
        protocol: ANDROID_PHONE # qq登录协议 支持 ANDROID_PHONE ANDROID_PAD ANDROID_WATCH
        device: device.json # 设备信息文件名
  logger:
    network: false # 是否在控制台显示bot的网络信息
    eventStatus: true # 是否在控制台打印事件执行失败信息 暂时不起作用
    debug: false # 是否在控制台打印事件解析信息 暂时不起作用
  alias: # 指令别名 将会自动注册 配置方式为 指令全名:别名
  configs: # 全局配置 所有全局配置均可以主动从GlobalConfig类中拿到 具体请看注释
    DEFAULT_COMMAND_START: "" # 默认指令开头 当@EventHandler中没有指定start时使用改配置
    DEFAULT_EVENT_NET_TIMEOUT: 300000 # 默认的上下文监听超时时间 5分钟
